import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Build a Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <header>
          <h1>Jane Goodall Institute</h1>
           <Link href="http://localhost:3000/">Home</Link> 
           <Link href="/ourstory">Our Story</Link> 
           <Link href="/contact">Contact</Link> 
           <Link href="/About">About</Link> 
           <Link href="/Wiki">Wiki</Link> 
        </header>
        <footer>
        <p>  “Every individual matters. Every individual has a role to play. Every individual makes a difference.” <br/>
      Dr. Jane Goodall <br/>
     1120 20th St. NW #520s, Washington, DC 20036 <br/>
Telephone: (703) 682-9220 | Fax: (703) 682-9312<br/>
© The Jane Goodall Institute 2024<br/>
Brand strategy & site design by Good, Unlimited. | Kite Inc.</p>
      
        </footer>
      </body>
    </html>
  );
}
